name: yopeio
favicon: null
layout_spectrum: 0.8755840787198395
typography_spectrum: 0.504000901710242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.795980176422745
  lightness: 0.986789062153548
  saturation: 0.760481474455446
  rhythmicContrast: 0.29830097733065486
purpose: []
