name: yopeio
favicon: null
layout_spectrum: 0.89232
typography_spectrum: 0.89692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070d1d'
    - '#0e4e5a'
    - '#0d9f92'
    - '#0c7372'
    - '#2fc6b3'
  brandStrength: 0
  lightness: 0.986789062153548
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
