name: yopeio
favicon: null
layout_spectrum: 0.6586
typography_spectrum: 0.01753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#6c6c6c'
    - '#363636'
    - '#9d9d9d'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
